/*
    Generic effective-divisor search for the X1(37) proof.

    This file implements the finite-field search used in Proposition 5.7
    for X_1(37).  The mathematical goal is to prove that W^0_9(C) over
    F_2 does not contain a translate of the order-5 subgroup generated by
    D0, where C is the F_2 model of X_1(37) and D0 is the difference of
    two pullback fibers from X_0^+(37).

    The driver passes the four nonzero translates

        deltas = [D0, 2*D0, 3*D0, 4*D0].

    For every effective F_2-rational divisor D of degree d, this code
    checks whether all classes D + delta are still represented by
    effective degree-d divisors.  Equivalently, for each delta it tests
    whether L(D + delta) is nonzero.  If every effective D is killed by at
    least one nonzero delta, then no translate of <D0> is contained in
    W^0_d(C).

    The search is chunked by "degree type" so that several Magma workers
    can run independently.  CHUNK_INDEX and NCHUNKS are set by the driver.
*/

/*
    Positive part of a divisor: keep only terms with positive valuation.
    This is used to split a degree-zero divisor delta into its positive
    and negative parts.
*/
function Pos(D, C)
    E := DivisorGroup(C)!0;
    for P in Support(D) do
        v := Valuation(D, P);
        if v gt 0 then E +:= v*P; end if;
    end for;
    return E;
end function;

/*
    Enumerate the possible degree types of effective F_2-rational
    divisors of total degree d.

    A type is a list of pairs <m, deg>.  Each pair represents one place
    of degree deg appearing with multiplicity m.  For example,

        [<2,1>, <1,3>]

    means 2*P + Q, with P rational and Q of degree 3.  The routine only
    uses degrees for which the curve actually has places.
*/
function DegreeTypes(d, places)
    ds := [i : i in [1..d] | #places[i] gt 0];
    old := [ <[<0,0>], d> ];
    new := old;
    done := [];
    for deg in Reverse(ds) do
        for m in Reverse([1..Floor(d/deg)]) do
            for t in old do
                for r in [1..Floor(t[2]/(m*deg))] do
                    Append(~new, <t[1] cat [<m,deg> : j in [1..r]], t[2] - m*deg*r>);
                end for;
            end for;
            done cat:= [t[1][2..#t[1]] : t in new | t[2] eq 0];
            new := [t : t in new | t[2] gt 0];
            old := new;
        end for;
    end for;
    seen := AssociativeArray(); keys := [];
    for t in done do
        key := Sprint(Sort([Sprint(x) : x in t]));
        if not IsDefined(seen, key) then seen[key] := t; Append(~keys, key); end if;
    end for;
    return [seen[k] : k in Sort(keys)];
end function;

/*
    Compress a degree type into groups <multiplicity, degree, count>.
    Stream below uses this to choose "count" distinct places of a fixed
    degree, all with the same multiplicity.
*/
function Groups(t)
    g := [];
    for a in t do
        found := false;
        for i in [1..#g] do
            if g[i][1] eq a[1] and g[i][2] eq a[2] then
                g[i] := <a[1], a[2], g[i][3] + 1>; found := true; break;
            end if;
        end for;
        if not found then Append(~g, <a[1], a[2], 1>); end if;
    end for;
    return g;
end function;

/*
    Write an element of a residue field as coordinates over the base field
    F.  A vanishing condition at a degree-r place is one equation over the
    residue field, hence r linear equations over F.
*/
function ResidueCoords(c, F)
    if Type(c) eq RngIntElt then return [F!c]; end if;
    if Parent(c) cmpeq F then return [F!c]; end if;
    ok, b := IsCoercible(F, c);
    if ok then return [b]; end if;
    v := [F | ];
    for a in Eltseq(c) do v cat:= ResidueCoords(a, F); end for;
    return v;
end function;

/*
    First n coefficients of the local expansion of h at P.

    The caller only asks for expansions after multiplying by a suitable
    power of a uniformizer, so h should be regular at P.  If it is not,
    Evaluate returns Infinity and the search stops with an error.
*/
function LocalCoeffs(h, P, n)
    u := LocalUniformizer(P); rem := h; coeffs := [];
    for i in [1..n] do
        c := Evaluate(rem, P);
        if c cmpeq Infinity() then error "non-regular local expansion"; end if;
        Append(~coeffs, c); rem := (rem - Lift(c, P))/u;
    end for;
    return coeffs;
end function;

/*
    Build the linear rows that force a section to vanish to prescribed
    order at P.

    fs is a basis of a Riemann-Roch space L(G).  The factor u^shift makes
    each basis element regular at P, where shift = v_P(G).  Each local
    coefficient gives Degree(P) scalar equations over F.
*/
function RowsAt(fs, P, shift, n, F)
    rows := [];
    cs := [LocalCoeffs(f*LocalUniformizer(P)^shift, P, n) : f in fs];
    for r in [1..n] do
        for a in [1..Degree(P)] do
            row := [F | ];
            for j in [1..#fs] do
                v := ResidueCoords(cs[j][r], F);
                Append(~row, a le #v select v[a] else F!0);
            end for;
            Append(~rows, row);
        end for;
    end for;
    return rows;
end function;

/*
    For one degree type, build a divisor H that dominates every divisor
    of that type.

    If the type uses degree deg places with multiplicities at most m, H
    contains m times every degree deg place on C.  This makes D <= H for
    every divisor D generated from the type.  We can then precompute
    Riemann-Roch data for H and impose linear conditions to specialize
    from H down to each individual D.
*/
function CoverDivisor(t, C, places)
    max := AssociativeArray();
    for a in t do
        if not IsDefined(max, a[2]) or a[1] gt max[a[2]] then max[a[2]] := a[1]; end if;
    end for;
    H := DivisorGroup(C)!0;
    for deg in Keys(max) do for P in places[deg] do H +:= max[deg]*P; end for; end for;
    return H;
end function;

/*
    Precompute the data needed to test L(D + delta) for all D <= H.

    Write delta = delta_plus - delta_minus.  Set

        G = H + delta_plus,     R = H + delta_minus.

    Every section of L(D + delta) lies in L(G).  To descend from L(G) to
    L(D + delta), it must vanish along R - D.  The tuple returned here is

        <#basis, support(R), valuations(R), basis functions,
         valuations(G), cached local rows, dim L(G), RR setup time>.
*/
function FastData(C, H, delta)
    G := H + Pos(delta, C);
    R := H + Pos(-delta, C);
    t := Cputime(); V, m := RiemannRochSpace(G); rr := Cputime(t);
    fs := [m(b) : b in Basis(V)];
    ps := []; ns := []; shifts := [];
    for P in Support(R) do
        n := Valuation(R, P);
        if n gt 0 then Append(~ps, P); Append(~ns, n); Append(~shifts, Valuation(G, P)); end if;
    end for;
    return <#fs, ps, ns, fs, shifts, AssociativeArray(), Dimension(V), rr>;
end function;

/*
    Replace only the cache component of a FastData tuple.
*/
function ReplaceCache(data, cache)
    return <data[1], data[2], data[3], data[4], data[5], cache, data[7], data[8]>;
end function;

/*
    Return, and cache, all local rows at the i-th place in support(R).
    Rows are independent of the particular D <= H; for a given D we just
    take an initial segment corresponding to the required vanishing order.
*/
function CachedRows(data, i, F)
    cache := data[6];
    if not IsDefined(cache, i) then cache[i] := RowsAt(data[4], data[2][i], data[5][i], data[3][i], F); end if;
    return ReplaceCache(data, cache), cache[i];
end function;

/*
    Decide whether the divisor class D + delta lies in W^0_d(C), using
    the precomputed data for the cover H of D's degree type.

    For each P in support(R), the required number of vanishing
    coefficients is

        v_P(R - D) = v_P(R) - v_P(D).

    The matrix assembled from these local conditions acts on the basis of
    L(G).  A nonzero kernel means L(D + delta) is nonzero, so the class is
    in W^0_d.  Full column rank means no such section exists.
*/
function FastInW0(D, data, F)
    ncols := data[1];
    if ncols eq 0 then return false, data; end if;
    jobs := [];
    for i in [1..#data[2]] do
        keep := data[3][i] - Valuation(D, data[2][i]);
        if keep lt 0 then error "cover divisor missed D"; end if;
        if keep gt 0 then Append(~jobs, <keep*Degree(data[2][i]), i>); end if;
    end for;
    if #jobs eq 0 then return true, data; end if;
    rows := []; nrows := 0;
    for job in Reverse(Sort(jobs)) do
        data, r := CachedRows(data, job[2], F);
        rows cat:= r[1..job[1]]; nrows +:= job[1];
        if nrows ge ncols and Rank(Matrix(F, #rows, ncols, &cat rows)) eq ncols then
            return false, data;
        end if;
    end for;
    return Rank(Matrix(F, #rows, ncols, &cat rows)) lt ncols, data;
end function;

/*
    Test one effective divisor D.

    D itself represents the zero translate and is already effective.  The
    loop checks the four nonzero translates.  If all of them are also in
    W^0_d, then this D is a potential translate of <D0> contained in
    W^0_d, so the chunk reports INCONCLUSIVE and stops immediately.
*/
procedure TestD(~survivors, ~stop, ~checked, D, deltas, labels, ~data, F, t0)
    checked +:= 1; bad := 0;
    for j in [1..#deltas] do
        ok, dj := FastInW0(D, data[j], F); data[j] := dj;
        if not ok then bad := j; break; end if;
    end for;
    if bad eq 0 then
        Append(~survivors, D);
        printf "SURVIVOR %o in chunk %o after %o tested divisors: %o\n", #survivors, CHUNK_INDEX, checked, D;
        print "INCONCLUSIVE: stopped after first survivor."; print "CHUNK_RESULT: INCONCLUSIVE"; stop := true;
    elif checked mod 1000 eq 0 then
        printf "Chunk %o checked %o divisors; last killed by %o; survivors %o; elapsed %o\n",
               CHUNK_INDEX, checked, labels[bad], #survivors, Cputime(t0);
    end if;
end procedure;

/*
    Recursively stream all effective divisors with a fixed degree type.

    The recursion avoids materializing the full list of divisors.  It
    chooses the required number of distinct places for each
    <multiplicity, degree> group, builds D incrementally, and calls TestD
    once the divisor has total degree d.
*/
procedure Stream(~survivors, ~stop, ~checked, groups, i, chosen, nextp, D, used, places, deltas, labels, ~data, F, t0)
    if stop then return; end if;
    if i gt #groups then TestD(~survivors, ~stop, ~checked, D, deltas, labels, ~data, F, t0); return; end if;
    mult := groups[i][1]; deg := groups[i][2]; need := groups[i][3];
    if chosen eq need then
        Stream(~survivors, ~stop, ~checked, groups, i+1, 0, 1, D, used, places, deltas, labels, ~data, F, t0); return;
    end if;
    last := #places[deg] - (need - chosen) + 1;
    for k in [nextp..last] do
        P := places[deg][k];
        if P notin used then
            Stream(~survivors, ~stop, ~checked, groups, i, chosen+1, k+1, D + mult*P,
                   used cat [P], places, deltas, labels, ~data, F, t0);
            if stop then break; end if;
        end if;
    end for;
end procedure;

/*
    Top-level search.

    The function enumerates all effective F_2-rational divisors of degree
    d on C by degree type.  Degree types are distributed over workers by
    the congruence

        (type_index - 1) mod NCHUNKS = CHUNK_INDEX.

    For each assigned type it builds one cover divisor H, precomputes the
    Riemann-Roch spaces attached to H + delta_plus, and streams all
    divisors of that type through the translate test.  It returns true
    exactly when this chunk found no divisor whose full nonzero translate
    set survived.
*/
function NoTranslate(C, d, deltas, labels)
    printf "Testing %o nonzero translates; chunk %o/%o.\n", #deltas, CHUNK_INDEX, NCHUNKS;
    places := AssociativeArray();
    for i in [1..d] do places[i] := Places(C, i); end for;
    types := DegreeTypes(d, places);
    mine := [i : i in [1..#types] | (i - 1) mod NCHUNKS eq CHUNK_INDEX];
    printf "Place counts by degree: %o\n", [#places[i] : i in [1..d]];
    printf "Degree types: %o; assigned %o\n", #types, mine;
    survivors := []; checked := 0; t0 := Cputime(); F := GF(2);
    for n in mine do
        g := Groups(types[n]); H := CoverDivisor(types[n], C, places);
        printf "Degree type %o/%o: %o; groups %o; elapsed %o\n", n, #types, types[n], g, Cputime(t0);
        data := [* *]; dims := []; times := [];
        for delta in deltas do
            D := FastData(C, H, delta); Append(~data, D); Append(~dims, D[7]); Append(~times, D[8]);
        end for;
        printf "Fast W0 setup: cover degree %o; dims %o; RR times %o\n", Degree(H), dims, times;
        stop := false;
        Stream(~survivors, ~stop, ~checked, g, 1, 0, 1, DivisorGroup(C)!0, [], places, deltas, labels, ~data, F, t0);
        if stop then return false, survivors; end if;
    end for;
    printf "Divisors tested in chunk %o: %o\n", CHUNK_INDEX, checked;
    printf "Surviving translates in this chunk: %o\n", #survivors;
    if #survivors eq 0 then print "SUCCESS: this chunk contains no translate survivor."; print "CHUNK_RESULT: SUCCESS"; return true, survivors; end if;
    print "INCONCLUSIVE: at least one quotient coset survived in this chunk."; print "CHUNK_RESULT: INCONCLUSIVE";
    return false, survivors;
end function;
